// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-recipes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/auth.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function timingSafeEqual(a, b) {
  const encoder = new TextEncoder();
  const aBytes = encoder.encode(a);
  const bBytes = encoder.encode(b);
  const length = Math.max(aBytes.length, bBytes.length);
  let diff = aBytes.length ^ bBytes.length;
  for (let i = 0; i < length; i++) {
    diff |= (aBytes[i] ?? 0) ^ (bBytes[i] ?? 0);
  }
  return diff === 0;
}
function requireApiKey(apiKey) {
  const expected = runtimeEnv("MCP_API_KEY")?.trim();
  if (!expected) {
    return {
      content: [
        { type: "text", text: "Server misconfiguration: MCP_API_KEY is not set." }
      ],
      isError: true
    };
  }
  const provided = typeof apiKey === "string" ? apiKey.trim() : "";
  if (!provided || !timingSafeEqual(provided, expected)) {
    return {
      content: [
        { type: "text", text: "Unauthorized: invalid or missing api_key." }
      ],
      isError: true
    };
  }
  return null;
}
function lovableApiKey() {
  const key = runtimeEnv("LOVABLE_API_KEY")?.trim();
  if (!key) throw new Error("LOVABLE_API_KEY is not configured");
  return key;
}

// src/lib/mcp/tools/search-recipes.ts
var search_recipes_default = defineTool({
  name: "search_recipes",
  title: "Search recipes",
  description: "Find complete cooking recipes that use a given list of ingredients, optionally scoped to a cuisine and scaled to a serving size.",
  inputSchema: {
    api_key: z.string().min(1).describe("Dishtail MCP API key."),
    ingredients: z.array(z.string().trim().min(1)).min(1).max(25).describe("Ingredients the recipe must use."),
    cuisine: z.string().trim().min(1).max(60).optional().describe("Optional cuisine, e.g. 'Italian'."),
    serving_size: z.number().int().min(1).max(20).default(1).describe("Number of people to serve.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ api_key, ingredients, cuisine, serving_size }) => {
    const denied = requireApiKey(api_key);
    if (denied) return denied;
    const servingSize = serving_size ?? 1;
    const cuisineInstruction = cuisine ? `Focus on ${cuisine} cuisine recipes.` : "You can suggest recipes from any cuisine.";
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${lovableApiKey()}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content: `You are a recipe expert. Respond with ONLY a valid JSON array of recipes, no markdown. Each recipe object has: title, description, ingredients (array of strings with quantities), instructions (array of steps), prepTime (e.g. "25 minutes"), dietType (one of Vegetarian, Eggetarian, Vegan, Non-Vegetarian), isHealthy (boolean), source ("Web Search").

DIET TYPE RULES:
- "Vegan": no animal products at all.
- "Vegetarian": no meat, fish or eggs; dairy allowed.
- "Eggetarian": vegetarian plus eggs. Any recipe with eggs and no meat/fish is Eggetarian, never Vegetarian.
- "Non-Vegetarian": contains meat, poultry, fish or seafood.

All ingredient quantities must be for ${servingSize} serving(s).`
          },
          {
            role: "user",
            content: `Find complete cooking recipes that use ALL of these ingredients: ${ingredients.join(", ")}.
${cuisineInstruction}
Serve ${servingSize} ${servingSize === 1 ? "person" : "people"}. Return 5-7 different recipes.`
          }
        ]
      })
    });
    if (!response.ok) {
      const detail = response.status === 429 ? "Rate limit exceeded, try again shortly." : response.status === 402 ? "AI credits exhausted for this workspace." : `Recipe search failed (${response.status}).`;
      return { content: [{ type: "text", text: detail }], isError: true };
    }
    const data = await response.json();
    const content = data.choices?.[0]?.message?.content ?? "";
    let recipes;
    try {
      recipes = JSON.parse(content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim());
      if (!Array.isArray(recipes)) throw new Error("not an array");
    } catch {
      return { content: [{ type: "text", text: "Could not parse recipe results." }], isError: true };
    }
    recipes = recipes.map((recipe) => {
      const allText = `${recipe.ingredients?.join(" ") ?? ""} ${recipe.title} ${recipe.description}`.toLowerCase();
      const hasEgg = /\begg[s]?\b|\bomelette\b|\bomelet\b|\bbhurji\b/.test(allText);
      const hasMeat = /\bchicken\b|\bmutton\b|\blamb\b|\bbeef\b|\bpork\b|\bfish\b|\bprawn\b|\bshrimp\b|\bcrab\b|\blobster\b|\bturkey\b|\bduck\b|\bbacon\b|\bham\b|\bsausage\b|\bseafood\b/.test(allText);
      let dietType = recipe.dietType;
      if (hasMeat) dietType = "Non-Vegetarian";
      else if (hasEgg && dietType === "Vegetarian") dietType = "Eggetarian";
      return { ...recipe, dietType };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(recipes, null, 2) }],
      structuredContent: { recipes, servingSize }
    };
  }
});

// src/lib/mcp/tools/analyze-nutrition.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var analyze_nutrition_default = defineTool2({
  name: "analyze_nutrition",
  title: "Analyze nutrition",
  description: "Estimate calories, macros, vitamins, minerals and health notes for a recipe, per serving.",
  inputSchema: {
    api_key: z2.string().min(1).describe("Dishtail MCP API key."),
    title: z2.string().trim().min(1).max(200).describe("Recipe name."),
    ingredients: z2.array(z2.string().trim().min(1)).min(1).max(60).describe("Ingredients with quantities."),
    serving_size: z2.number().int().min(1).max(20).default(1).describe("Number of servings.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ api_key, title, ingredients, serving_size }) => {
    const denied = requireApiKey(api_key);
    if (denied) return denied;
    const servingSize = serving_size ?? 1;
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${lovableApiKey()}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content: "You are a nutrition expert. Provide accurate nutritional analysis based on standard ingredient databases. Always respond with valid JSON only, no markdown or extra text."
          },
          {
            role: "user",
            content: `Analyze the nutritional content of this recipe for ${servingSize} serving(s).

Recipe: ${title}
Ingredients: ${ingredients.join(", ")}

Respond as JSON:
{
  "calories": "estimated calories per serving",
  "macros": { "protein": "g", "carbs": "g", "fat": "g", "fiber": "g" },
  "vitamins": ["..."],
  "minerals": ["..."],
  "healthBenefits": ["..."],
  "considerations": ["..."],
  "healthScore": "1-10 rating",
  "summary": "brief 2-3 sentence summary"
}`
          }
        ]
      })
    });
    if (!response.ok) {
      const detail = response.status === 429 ? "Rate limit exceeded, try again shortly." : response.status === 402 ? "AI credits exhausted for this workspace." : `Nutrition analysis failed (${response.status}).`;
      return { content: [{ type: "text", text: detail }], isError: true };
    }
    const data = await response.json();
    const content = data.choices?.[0]?.message?.content ?? "";
    const match = content.match(/\{[\s\S]*\}/);
    if (!match) {
      return { content: [{ type: "text", text: "Could not parse nutrition results." }], isError: true };
    }
    let nutrition;
    try {
      nutrition = JSON.parse(match[0]);
    } catch {
      return { content: [{ type: "text", text: "Could not parse nutrition results." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(nutrition, null, 2) }],
      structuredContent: { nutrition, servingSize }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dishtail",
  title: "Dishtail",
  version: "0.1.0",
  instructions: "Tools for Dishtail, a recipe finder. Use `search_recipes` to find recipes from a list of ingredients and `analyze_nutrition` to estimate a recipe's nutrition per serving. Every tool requires the `api_key` argument holding the Dishtail MCP API key.",
  tools: [search_recipes_default, analyze_nutrition_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
